### PR TITLE
[REF] Git clone with pull request when no exist folder

### PR DESCRIPTION
**Pull request by JesusZapata**
Git clone when ${REPO_REQUIREMENTS} not exist

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 
I made test locally

image

image

**Comment by JesusZapata** [comment]
@moylop260 
The two new record on .travis.yml is green https://travis-ci.org/Vauxoo/maintainer-quality-tools/jobs/202003425 and https://travis-ci.org/Vauxoo/maintainer-quality-tools/jobs/202003428

Travis is in red for isolated mistakes

**Comment by moylop260** [comment]
Do you have the issue related?
(I didn't remember why we are creating this change)

**Comment by JesusZapata** [comment]
@moylop260 
The first incidence it was https://github.com/Vauxoo/maintainer-quality-tools/pull/183
After we decided to refactor the code to avoid duplicate code and add in .travis.yml lines to test this refactoring

**Comment by JesusZapata** [comment]
@moylop260 
What do you think about this PR?
The travis is red for isolated case of the lint check

**Comment by JesusZapata** [comment]
@moylop260 
In this PR fix when `PULL_REQUEST` is null for example in one `t2d` build
Recently the follow  PR https://github.com/vauxoo-dev/odoo-average/pull/1 he has the same problem

**Comment by hbto** [comment]
👍

**Pull request merged**
