### PR TITLE
[IMP] Auto-Install odoolint, web_environment_ribbon and odoo-profiler modules for 10.0

### PR DESCRIPTION
**Pull request by hugho-ad**
FIX https://github.com/Vauxoo/maintainer-quality-tools/issues/192
FIX https://github.com/Vauxoo/server-tools/issues/92

DUMMY https://github.com/Vauxoo/imeqmo/pull/111

### CODE REVIEW

**Comment by hugho-ad** [comment]
Not necessary, because this [patch](https://github.com/Vauxoo/odoo-profiler/pull/9/files#diff-a7f10d80983e87fce36e5c925d1f1642R28) make it not longer necessary

This pr will be converted on a Dummypr  in order to clone https://github.com/Vauxoo/odoo-profiler/pull/9

**Comment by hugho-ad** [comment]
@moylop260 can you review please

This is the pr dummy https://github.com/Vauxoo/imeqmo/pull/111

**Comment by moylop260** [comment]
Excellent thank you!
FYI the pgbader result is empty.

The PGOPTIONS environment variable is not set.

**Comment by hugho-ad** [comment]
Thaks moy, I missed integrate that part, 
I'll wok on it

**Comment by hugho-ad** [comment]
@moylop260 this is ready to merge after [this pr](https://github.com/Vauxoo/odoo-profiler/pull/11
) was merged

**Comment by moylop260** [comment]
After https://github.com/Vauxoo/server-tools/pull/95 too

**Pull request merged**
