### PR TITLE
[FIX] travis: apply patch for duplicate-code issue for any pylint version

### PR DESCRIPTION
**Pull request by fernandahf**
Description of the issue/feature this PR addresses:

The duplicate-code (R0801) can't be disabled
More information: https://github.com/PyCQA/pylint/issues/214

Current behavior before PR:
duplicated-code check can't be disabled.

Desired behavior after PR is merged:
duplicated-code check can be disabled.

-- I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by fernandahf** [comment]
@moylop260 

Could you review this, please?

Regards.

**Comment by moylop260** [comment]
Could you make a PR dummy in order to test this one, please?

**Comment by moylop260** [comment]
FYI I have created a t2d using this dev branch

And the original patch is outdated since that it is failing applying the first hunk

```
added 8 packages from 7 contributors, removed 5 packages and updated 21 packages in 15.757s
python -c "from __future__ import print_function; from pylint.checkers import similar; print(similar.__file__.rstrip('c'))"
patching file /.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/pylint/checkers/similar.py
Hunk #1 FAILED at 46.
Hunk #2 succeeded at 64 (offset 4 lines).
Hunk #3 succeeded at 157 with fuzz 1 (offset 4 lines).
Hunk #4 succeeded at 178 with fuzz 1 (offset 4 lines).
Hunk #5 succeeded at 214 (offset 4 lines).
Hunk #6 succeeded at 377 (offset 4 lines).
1 out of 6 hunks FAILED -- saving rejects to file /.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/pylint/checkers/similar.py.rej
```

Could you overwrite the patch with an updated one, please?

**Comment by moylop260** [comment]
We should be able to fix the following versions:
 - https://github.com/Vauxoo/pylint-odoo/blob/4024d6d4225f46b346959fbb70d5513f82e95f1a/requirements.txt#L7-L8

**Comment by fernandahf** [comment]
> FYI I have created a t2d using this dev branch
> 
> And the original patch is outdated since that it is failing applying the first hunk
> 
> ```
> added 8 packages from 7 contributors, removed 5 packages and updated 21 packages in 15.757s
> python -c "from __future__ import print_function; from pylint.checkers import similar; print(similar.__file__.rstrip('c'))"
> patching file /.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/pylint/checkers/similar.py
> Hunk #1 FAILED at 46.
> Hunk #2 succeeded at 64 (offset 4 lines).
> Hunk #3 succeeded at 157 with fuzz 1 (offset 4 lines).
> Hunk #4 succeeded at 178 with fuzz 1 (offset 4 lines).
> Hunk #5 succeeded at 214 (offset 4 lines).
> Hunk #6 succeeded at 377 (offset 4 lines).
> 1 out of 6 hunks FAILED -- saving rejects to file /.repo_requirements/virtualenv/python3.6/lib/python3.6/site-packages/pylint/checkers/similar.py.rej
> ```
> 
> Could you overwrite the patch with an updated one, please?

Done

**Comment by moylop260** [comment]
Could you make a dummy PR using this branch and using python2.7 and another using python3.6, please?

**Review by moylop260 — APPROVED** [review]
👍

**Pull request merged**
