### PR TITLE
[IMP] Adding environment variable opcional ODOO BRANCH for custom branch of odoo

### PR DESCRIPTION
**Pull request by JesusZapata**
Referring to https://github.com/Vauxoo/maintainer-quality-tools/issues/178

### CODE REVIEW

**Comment by JesusZapata** [comment]
@moylop260 
Should add entry in matrix in .travis.yml for test this functionality ?
How should test this issue?
I only tried it locally and work fine

**Comment by JesusZapata** [comment]
image

**Comment by moylop260** [comment]
@ruiztulio FYI

**Comment by moylop260** [comment]
@JesusZapata Use this commit for https://github.com/OCA/maintainer-quality-tools/pull/428

**Comment by ruiztulio** [comment]
@moylop260 I have a question, how does this change works? because we are using:

 ```ODOO_BRANCH: "vauxoo/odoo#saas-14"```

so we have the repo and the branch, with this changes do we only have to write ```ODOO_BRANCH: "saas-14"``` instead?

**Comment by moylop260** [comment]
Could you try with the following code:

```bash
ODOO_REPO: "vauxoo/odoo"
ODOO_BRANCH: "saas-14"
VERSION: "10.0"
```

**Pull request merged**
